# Default initial positions for dual_robots_config's ros2_control fake system

initial_positions:
  alice_elbow_joint: 0
  alice_robotiq_85_left_knuckle_joint: 0.78
  alice_shoulder_lift_joint: -1.57
  alice_shoulder_pan_joint: 0
  alice_wrist_1_joint: -1.57
  alice_wrist_2_joint: 0
  alice_wrist_3_joint: 0
  bob_elbow_joint: 0
  bob_robotiq_85_left_knuckle_joint: 0.78
  bob_shoulder_lift_joint: -1.57
  bob_shoulder_pan_joint: 0
  bob_wrist_1_joint: -1.57
  bob_wrist_2_joint: 0
  bob_wrist_3_joint: 0