ur_manipulator:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  #solve_type: Distance
  kinematics_solver_search_resolution: 0.0050000000000000001
  kinematics_solver_timeout: 0.0050000000000000001

# goal_joint_tolerance: 0.0001
# goal_position_tolerance: 0.0001
# goal_orientation_tolerance: 0.0001
#these factors are defined here
# based on https://www.youtube.com/watch?v=ME4wBbGbQHU&t=1055s
